# Parte 1: Introducción a R (continuación)

**Profesor:** Rodrigo Morales <br>
**E-mail:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo.
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.

 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [ ]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix( c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A

B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B

In [1]:
matrix( c(1,1,2,3,5,8), ncol = 3, nrow = 2)

[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

In [8]:


m1 <- matrix(1:100,nrow = 20, ncol = 5, byrow = T)

m2 <- matrix(1:100,nrow = 20, ncol = 5, byrow = F)

In [ ]:
# clase y atributo dim

[1] "matrix" "array"

[1] 2 3

In [ ]:
# Genere dos vectores del mismo largo y forme una matriz.

v1 <- 1:10
v2 <- 15:24


cbind(v1, v2)

rbind(v1, v2)


[1]  1  2  3  4  5  6  7  8  9 10

[1] 15 16 17 18 19 20 21 22 23 24

v1 v2
 [1,]  1 15
 [2,]  2 16
 [3,]  3 17
 [4,]  4 18
 [5,]  5 19
 [6,]  6 20
 [7,]  7 21
 [8,]  8 22
 [9,]  9 23
[10,] 10 24

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
v1  1    2    3    4    5    6    7    8    9   10   
v2 15   16   17   18   19   20   21   22   23   24

Funciones cbind() y rbind() 

In [ ]:
# NOTA: Podemos añadir una fila/columna a una matriz existente

v1 <- 100:119

cbind(m1, v1)

colnames(m1) <- letters[1:5]

rownames(m1) <- LETTERS[1:20]

m1

a  b  c  d  e   v1 
 [1,]  1  2  3  4   5 100
 [2,]  6  7  8  9  10 101
 [3,] 11 12 13 14  15 102
 [4,] 16 17 18 19  20 103
 [5,] 21 22 23 24  25 104
 [6,] 26 27 28 29  30 105
 [7,] 31 32 33 34  35 106
 [8,] 36 37 38 39  40 107
 [9,] 41 42 43 44  45 108
[10,] 46 47 48 49  50 109
[11,] 51 52 53 54  55 110
[12,] 56 57 58 59  60 111
[13,] 61 62 63 64  65 112
[14,] 66 67 68 69  70 113
[15,] 71 72 73 74  75 114
[16,] 76 77 78 79  80 115
[17,] 81 82 83 84  85 116
[18,] 86 87 88 89  90 117
[19,] 91 92 93 94  95 118
[20,] 96 97 98 99 100 119

a  b  c  d  e  
A  1  2  3  4   5
B  6  7  8  9  10
C 11 12 13 14  15
D 16 17 18 19  20
E 21 22 23 24  25
F 26 27 28 29  30
G 31 32 33 34  35
H 36 37 38 39  40
I 41 42 43 44  45
J 46 47 48 49  50
K 51 52 53 54  55
L 56 57 58 59  60
M 61 62 63 64  65
N 66 67 68 69  70
O 71 72 73 74  75
P 76 77 78 79  80
Q 81 82 83 84  85
R 86 87 88 89  90
S 91 92 93 94  95
T 96 97 98 99 100

Matrices diagonales

In [40]:
#?diag

diag(c(1,2,3))


[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

Acceso a elementos de una matriz

In [43]:

# acceder a la posicion 10, 5
#posicion
m1[ 10 , 5 ] 


[1] 50

In [44]:


# por condicion lógica

m1[ , m1[1,] >= 10 ]





A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T

Acceso a Filas y columnas

In [47]:
#Recordemos que podemos actualizar elementos de un vector como:

m1[ 10 , 5 ] 

m1[ 10 , 5 ] = 100

m1

[1] 100

a  b  c  d  e  
A  1  2  3  4   5
B  6  7  8  9  10
C 11 12 13 14  15
D 16 17 18 19  20
E 21 22 23 24  25
F 26 27 28 29  30
G 31 32 33 34  35
H 36 37 38 39  40
I 41 42 43 44  45
J 46 47 48 49 100
K 51 52 53 54  55
L 56 57 58 59  60
M 61 62 63 64  65
N 66 67 68 69  70
O 71 72 73 74  75
P 76 77 78 79  80
Q 81 82 83 84  85
R 86 87 88 89  90
S 91 92 93 94  95
T 96 97 98 99 100

Acceso mediante nombres

In [ ]:
# Acceso mediante nombres

m1[ "J", "e"]

m1[ c("A", "B", "D"), "e"]

Acceso mediante "indicatrices" lógicas

In [ ]:
#Quiero obtener los elementos (1,1) y (2,3) de M3
# 1: Crear una matriz de 3x4 con TRUE en dichas posiciones y FALSE en las restantes.


In [ ]:
# Podemos evaluar las casillas de una matriz mediante sentencias lógicas


### **Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %\*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [ ]:
# Álgbra de matrices  ------------

m1 + m2

m1 * m2 #-> no es la multiplicacion matricial

m1 #-> 20 filas, 5 columans
m2 #-> 20 filas, 5 columans


m1 %*% t(m2) #(20, 5) x (5, 20) -> 20, 20 -> multiplicación matricial

#(20, 5) x (5, 50) -> 20, 50
m3 <- matrix(1:250,nrow = 5, ncol = 50)
m3


m1 %*% m3

a   b   c   d   e  
A   2  23  44  65  86
B   8  29  50  71  92
C  14  35  56  77  98
D  20  41  62  83 104
E  26  47  68  89 110
F  32  53  74  95 116
G  38  59  80 101 122
H  44  65  86 107 128
I  50  71  92 113 134
J  56  77  98 119 140
K  62  83 104 125 146
L  68  89 110 131 152
M  74  95 116 137 158
N  80 101 122 143 164
O  86 107 128 149 170
P  92 113 134 155 176
Q  98 119 140 161 182
R 104 125 146 167 188
S 110 131 152 173 194
T 116 137 158 179 200

a    b    c    d    e    
A    1   42  123  244   405
B   12  154  336  558   820
C   33  276  559  882  1245
D   64  408  792 1216  1680
E  105  550 1035 1560  2125
F  156  702 1288 1914  2580
G  217  864 1551 2278  3045
H  288 1036 1824 2652  3520
I  369 1218 2107 3036  4005
J  460 1410 2400 3430  4500
K  561 1612 2703 3834  5005
L  672 1824 3016 4248  5520
M  793 2046 3339 4672  6045
N  924 2278 3672 5106  6580
O 1065 2520 4015 5550  7125
P 1216 2772 4368 6004  7680
Q 1377 3034 4731 6468  8245
R 1548 3306 5104 6942  8820
S 1729 3588 5487 7426  9405
T 1920 3880 5880 7920 10000

a  b  c  d  e  
A  1  2  3  4   5
B  6  7  8  9  10
C 11 12 13 14  15
D 16 17 18 19  20
E 21 22 23 24  25
F 26 27 28 29  30
G 31 32 33 34  35
H 36 37 38 39  40
I 41 42 43 44  45
J 46 47 48 49  50
K 51 52 53 54  55
L 56 57 58 59  60
M 61 62 63 64  65
N 66 67 68 69  70
O 71 72 73 74  75
P 76 77 78 79  80
Q 81 82 83 84  85
R 86 87 88 89  90
S 91 92 93 94  95
T 96 97 98 99 100

[,1] [,2] [,3] [,4] [,5]
 [1,]  1   21   41   61    81 
 [2,]  2   22   42   62    82 
 [3,]  3   23   43   63    83 
 [4,]  4   24   44   64    84 
 [5,]  5   25   45   65    85 
 [6,]  6   26   46   66    86 
 [7,]  7   27   47   67    87 
 [8,]  8   28   48   68    88 
 [9,]  9   29   49   69    89 
[10,] 10   30   50   70    90 
[11,] 11   31   51   71    91 
[12,] 12   32   52   72    92 
[13,] 13   33   53   73    93 
[14,] 14   34   54   74    94 
[15,] 15   35   55   75    95 
[16,] 16   36   56   76    96 
[17,] 17   37   57   77    97 
[18,] 18   38   58   78    98 
[19,] 19   39   59   79    99 
[20,] 20   40   60   80   100

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10] [,11] [,12] [,13]
A   815   830   845   860   875   890   905   920   935   950   965   980   995
B  1840  1880  1920  1960  2000  2040  2080  2120  2160  2200  2240  2280  2320
C  2865  2930  2995  3060  3125  3190  3255  3320  3385  3450  3515  3580  3645
D  3890  3980  4070  4160  4250  4340  4430  4520  4610  4700  4790  4880  4970
E  4915  5030  5145  5260  5375  5490  5605  5720  5835  5950  6065  6180  6295
F  5940  6080  6220  6360  6500  6640  6780  6920  7060  7200  7340  7480  7620
G  6965  7130  7295  7460  7625  7790  7955  8120  8285  8450  8615  8780  8945
H  7990  8180  8370  8560  8750  8940  9130  9320  9510  9700  9890 10080 10270
I  9015  9230  9445  9660  9875 10090 10305 10520 10735 10950 11165 11380 11595
J 10040 10280 10520 10760 11000 11240 11480 11720 11960 12200 12440 12680 12920
K 11065 11330 11595 11860 12125 12390 12655 12920 13185 13450 13715 13980 14245
L 12090 12380 12670 12960 13250 13540 13830 14120 14410 14700 14990 15280 15570
M 13115 13430 13745 14060 14375 14690 15005 15320 15635 15950 16265 16580 16895
N 14140 14480 14820 15160 15500 15840 16180 16520 16860 17200 17540 17880 18220
O 15165 15530 15895 16260 16625 16990 17355 17720 18085 18450 18815 19180 19545
P 16190 16580 16970 17360 17750 18140 18530 18920 19310 19700 20090 20480 20870
Q 17215 17630 18045 18460 18875 19290 19705 20120 20535 20950 21365 21780 22195
R 18240 18680 19120 19560 20000 20440 20880 21320 21760 22200 22640 23080 23520
S 19265 19730 20195 20660 21125 21590 22055 22520 22985 23450 23915 24380 24845
T 20290 20780 21270 21760 22250 22740 23230 23720 24210 24700 25190 25680 26170
  [,14] [,15] [,16] [,17] [,18] [,19] [,20]
A  1010  1025  1040  1055  1070  1085  1100
B  2360  2400  2440  2480  2520  2560  2600
C  3710  3775  3840  3905  3970  4035  4100
D  5060  5150  5240  5330  5420  5510  5600
E  6410  6525  6640  6755  6870  6985  7100
F  7760  7900  8040  8180  8320  8460  8600
G  9110  9275  9440  9605  9770  9935 10100
H 10460 10650 10840 11030 11220 11410 11600
I 11810 12025 12240 12455 12670 12885 13100
J 13160 13400 13640 13880 14120 14360 14600
K 14510 14775 15040 15305 15570 15835 16100
L 15860 16150 16440 16730 17020 17310 17600
M 17210 17525 17840 18155 18470 18785 19100
N 18560 18900 19240 19580 19920 20260 20600
O 19910 20275 20640 21005 21370 21735 22100
P 21260 21650 22040 22430 22820 23210 23600
Q 22610 23025 23440 23855 24270 24685 25100
R 23960 24400 24840 25280 25720 26160 26600
S 25310 25775 26240 26705 27170 27635 28100
T 26660 27150 27640 28130 28620 29110 29600

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1     6   11   16   21   26   31   36   41   46    ⋯     201   206   211  
[2,] 2     7   12   17   22   27   32   37   42   47    ⋯     202   207   212  
[3,] 3     8   13   18   23   28   33   38   43   48    ⋯     203   208   213  
[4,] 4     9   14   19   24   29   34   39   44   49    ⋯     204   209   214  
[5,] 5    10   15   20   25   30   35   40   45   50    ⋯     205   210   215  
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 216   221   226   231   236   241   246  
[2,] 217   222   227   232   237   242   247  
[3,] 218   223   228   233   238   243   248  
[4,] 219   224   229   234   239   244   249  
[5,] 220   225   230   235   240   245   250

[,1] [,2] [,3] [,4] [,5]  [,6]  [,7]  [,8]  [,9]  [,10] [,11] [,12] [,13] 
A   55  130  205  280   355   430   505   580   655   730 ⋯      3055   3130
B  130  330  530  730   930  1130  1330  1530  1730  1930 ⋯      8130   8330
C  205  530  855 1180  1505  1830  2155  2480  2805  3130 ⋯     13205  13530
D  280  730 1180 1630  2080  2530  2980  3430  3880  4330 ⋯     18280  18730
E  355  930 1505 2080  2655  3230  3805  4380  4955  5530 ⋯     23355  23930
F  430 1130 1830 2530  3230  3930  4630  5330  6030  6730 ⋯     28430  29130
G  505 1330 2155 2980  3805  4630  5455  6280  7105  7930 ⋯     33505  34330
H  580 1530 2480 3430  4380  5330  6280  7230  8180  9130 ⋯     38580  39530
I  655 1730 2805 3880  4955  6030  7105  8180  9255 10330 ⋯     43655  44730
J  730 1930 3130 4330  5530  6730  7930  9130 10330 11530 ⋯     48730  49930
K  805 2130 3455 4780  6105  7430  8755 10080 11405 12730 ⋯     53805  55130
L  880 2330 3780 5230  6680  8130  9580 11030 12480 13930 ⋯     58880  60330
M  955 2530 4105 5680  7255  8830 10405 11980 13555 15130 ⋯     63955  65530
N 1030 2730 4430 6130  7830  9530 11230 12930 14630 16330 ⋯     69030  70730
O 1105 2930 4755 6580  8405 10230 12055 13880 15705 17530 ⋯     74105  75930
P 1180 3130 5080 7030  8980 10930 12880 14830 16780 18730 ⋯     79180  81130
Q 1255 3330 5405 7480  9555 11630 13705 15780 17855 19930 ⋯     84255  86330
R 1330 3530 5730 7930 10130 12330 14530 16730 18930 21130 ⋯     89330  91530
S 1405 3730 6055 8380 10705 13030 15355 17680 20005 22330 ⋯     94405  96730
T 1480 3930 6380 8830 11280 13730 16180 18630 21080 23530 ⋯     99480 101930
  [,14]  [,15]  [,16]  [,17]  [,18]  [,19]  [,20]  [,21] 
A   3205   3280   3355   3430   3505   3580   3655   3730
B   8530   8730   8930   9130   9330   9530   9730   9930
C  13855  14180  14505  14830  15155  15480  15805  16130
D  19180  19630  20080  20530  20980  21430  21880  22330
E  24505  25080  25655  26230  26805  27380  27955  28530
F  29830  30530  31230  31930  32630  33330  34030  34730
G  35155  35980  36805  37630  38455  39280  40105  40930
H  40480  41430  42380  43330  44280  45230  46180  47130
I  45805  46880  47955  49030  50105  51180  52255  53330
J  51130  52330  53530  54730  55930  57130  58330  59530
K  56455  57780  59105  60430  61755  63080  64405  65730
L  61780  63230  64680  66130  67580  69030  70480  71930
M  67105  68680  70255  71830  73405  74980  76555  78130
N  72430  74130  75830  77530  79230  80930  82630  84330
O  77755  79580  81405  83230  85055  86880  88705  90530
P  83080  85030  86980  88930  90880  92830  94780  96730
Q  88405  90480  92555  94630  96705  98780 100855 102930
R  93730  95930  98130 100330 102530 104730 106930 109130
S  99055 101380 103705 106030 108355 110680 113005 115330
T 104380 106830 109280 111730 114180 116630 119080 121530

In [49]:
# Multiplicación de matrices
m1 * m2 # multiplicación componente a componente


a    b    c    d    e    
A    1   42  123  244   405
B   12  154  336  558   820
C   33  276  559  882  1245
D   64  408  792 1216  1680
E  105  550 1035 1560  2125
F  156  702 1288 1914  2580
G  217  864 1551 2278  3045
H  288 1036 1824 2652  3520
I  369 1218 2107 3036  4005
J  460 1410 2400 3430  9000
K  561 1612 2703 3834  5005
L  672 1824 3016 4248  5520
M  793 2046 3339 4672  6045
N  924 2278 3672 5106  6580
O 1065 2520 4015 5550  7125
P 1216 2772 4368 6004  7680
Q 1377 3034 4731 6468  8245
R 1548 3306 5104 6942  8820
S 1729 3588 5487 7426  9405
T 1920 3880 5880 7920 10000

### Matriz Transpuesta
Transponer una matriz consiste en **intercambiar sus filas por columnas**. Es decir, el elemento en la posición `[i, j]` pasa a la posición `[j, i]`.

**¿Para qué sirve?**
- En álgebra lineal, se usa para definir propiedades como **simetría**.
- En modelos estadísticos, ayuda a reorganizar datos para el cálculo de productos matriciales.
- En machine learning, se usa para ajustar dimensiones en operaciones de entrenamiento.

```r
# Ejemplo en R:
A <- matrix(1:6, nrow=2)
t(A)  # Transpuesta de A
```

In [29]:
# transponer una matriz
m1

t(m1)


a  b  c  d  e  
A  1  2  3  4   5
B  6  7  8  9  10
C 11 12 13 14  15
D 16 17 18 19  20
E 21 22 23 24  25
F 26 27 28 29  30
G 31 32 33 34  35
H 36 37 38 39  40
I 41 42 43 44  45
J 46 47 48 49  50
K 51 52 53 54  55
L 56 57 58 59  60
M 61 62 63 64  65
N 66 67 68 69  70
O 71 72 73 74  75
P 76 77 78 79  80
Q 81 82 83 84  85
R 86 87 88 89  90
S 91 92 93 94  95
T 96 97 98 99 100

A B  C  D  E  F  G  H  I  J  K  L  M  N  O  P  Q  R  S  T  
a 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91  96
b 2  7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92  97
c 3  8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93  98
d 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94  99
e 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100

### Determinante de una Matriz
El **determinante** es un número que se asocia a una matriz cuadrada. Proporciona información sobre las propiedades de esa matriz.

**¿Para qué sirve?**
- **Invertibilidad**: si el determinante es 0, la matriz **no tiene inversa**.
- **Volumen**: en geometría, representa cómo cambia el volumen bajo una transformación lineal.
- **Estabilidad numérica**: útil en modelos estadísticos para evitar problemas con matrices singulares.

```r
# Ejemplo en R:
A <- matrix(c(4,7,2,6), nrow=2)
det(A)  # Determinante de A
```


In [31]:
m4 <- matrix(1:16, 4, 4)

det(m4)

[1] 0

### Matriz Inversa
La **inversa** de una matriz cuadrada `A` es otra matriz `A⁻¹` tal que:

`A %*% A⁻¹ = I`, donde `I` es la matriz identidad.

**¿Para qué sirve?**
- Resolver sistemas de ecuaciones lineales.
- En regresión lineal, se utiliza en la fórmula del estimador de mínimos cuadrados.
- Representa un tipo de “deshacer” la transformación aplicada por una matriz.

```r
# Ejemplo en R:
A <- matrix(c(4,7,2,6), nrow=2)
solve(A)  # Matriz inversa de A
```



In [33]:
diag(c(1,1,1,1))

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

In [ ]:
m5 <- matrix(c(1,4,7,0,5,8,0,0,9), ncol= 3, nrow=3, byrow = T)



solve(m5)%*%m5

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 0    5    8   
[3,] 0    0    9

[,1] [,2]          [,3]         
[1,] 1    -2.220446e-16 -2.220446e-16
[2,] 0     1.000000e+00  2.775558e-16
[3,] 0     0.000000e+00  1.000000e+00

In [ ]:
# buscar ejemplo matriz

In [50]:
v1 <- 1:5
v2 <- 1:10

v1;v2

[1] 1 2 3 4 5

[1]  1  2  3  4  5  6  7  8  9 10

In [53]:
m3 <- cbind(v1, v2)
m3

v1 v2
 [1,] 1   1
 [2,] 2   2
 [3,] 3   3
 [4,] 4   4
 [5,] 5   5
 [6,] 1   6
 [7,] 2   7
 [8,] 3   8
 [9,] 4   9
[10,] 5  10

In [ ]:
v1[1] <- 100
v1

[1] 100   2   3   4   5

In [59]:
m3[5 , 2] <- 8

m3[5 , 2] = 8

#matrix(data = ,nrow = ,ncol = )

m3

v1 v2
 [1,] 1   1
 [2,] 2   2
 [3,] 3   3
 [4,] 4   4
 [5,] 5   8
 [6,] 1   6
 [7,] 2   7
 [8,] 3   8
 [9,] 4   9
[10,] 5  10

In [ ]:
#<- simbolo de asignacion
#= igualdad